# docker buildx build -f Dockerfile-builder -t ghcr.io/wasmvision/wasmvision-static-builder --platform linux/amd64,linux/arm64 --load .
#
# running:
# docker run --rm -v $(pwd):/src -v $(pwd)/build/amd64/:/build -a stdout -a stderr --platform linux/amd64 ghcr.io/wasmvision/wasmvision-static-builder
FROM ghcr.io/hybridgroup/opencv:4.10.0-static AS wasmvision-static-builder

WORKDIR /src

CMD go build -ldflags "-linkmode 'external' -extldflags '-static'" -tags netgo,osusergo,opencvstatic -o /build/wasmvision -buildvcs=false ./cmd/wasmvision
