name: macOS
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Install Dependencies
        run: |
          rm /usr/local/bin/2to3*
          rm /usr/local/bin/idle3*
          rm /usr/local/bin/pydoc*
          rm /usr/local/bin/python3*
          brew unlink pkg-config@0.29.2
          brew install opencv
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      - name: Run tests
        run: go test -v ./...
      - name: Build wasmVision binary
        run: |
          go build -o ./build/wasmvision ./cmd/wasmvision
      - name: Archive wasmvision binary
        uses: actions/upload-artifact@v4
        with:
          name: wasmvision-macos-arm64
          path: ./build/wasmvision
